version: '2'

services:
    burp:
        container_name: burp
        build: burp/
        ports:
            - "8080:8080"
        environment:
            DISPLAY: ${LOCAL_IP}:0
        command: java -jar -Xmx1024m /home/tester/sources/burpsuite.jar
